import React, { Component } from 'react';
import "./coop.css";
import CoopTile from '../../utils/coop-tile';

class Coop extends Component {
    constructor() {
        super();
        this.state = {
            data: null,
        };
    }

    render() {
        var tile_list =[];
        for (var i = 0; i < 2; i++){
            var semester = coop_data[i]["semester"]
            var company = coop_data[i]["company"]
            var details = coop_data[i]["details"]
            var position = coop_data[i]["position"]
            var skills = coop_data[i]["skills"]
            var intro = coop_data[i]["intro"]
            console.log(details)
            tile_list.push(<CoopTile semester={semester} company={company} details={details} position={position} skills={skills} intro={intro}/>)
        }
        return (
            <div>
                <h1 className="header">Co-op & Experience</h1>
                <div className="tiles">
                    {tile_list}
                </div>
            </div>
        )
    }
}

const coop_data =[
    {
        "number": 1,
        "semester": "Spring 2018",
        "company": "Siemens PLM Software",
        "position": "Strategic Student Co-op",
        // eslint-disable-next-line
        "intro" : "This was my first semester at Siemens and co-oping overall. \
            I learned about Software Development, how to maintain code and the Agile Methodology. \
            My main project was developing a CodeCoverage Dashboard for Software Developers and Managers using Code Coverage \
            data generated by test suites. I gained alot of experience with Database queries, API calls, Frontend Development, \
            and big data.",
        "details": [
            {id: 1, detail: "Used Angular2 to create a web dashboard"},
            {id: 2, detail: "Wrote python code to generate and organize CodeCoverage data"},
            {id: 3, detail: "Worked with Neo4j for big data visualization"}
        ],
        "skills" : "Angular2, Git, Neo4j, Python, Web Development"
    },
    {
        "number": 2,
        "semester": "Fall 2018",
        "company": "Siemens PLM Software",
        "position": "Strategic Student Co-op",
        // eslint-disable-next-line
        "intro" : "My second semester at Siemens strengthened my skills in Software Development, especially in creating and \
            maintaining a code base. I practiced Agile in my day to day work and preseneted in sprint reviews. \
            My main project was creating a Machine Learning software that utilized Google's TensorFlow library for Python. \
            This software was a proof of concept for determining the risk factor of a submitted code change based on specific factors. \
            I gained experience using Machine Learning (TensorFlow), Frontend Development, Backend Development, and database queries.",
        "details": [
            {id: 1, detail: "Created a code-change Risk Tool"},
            {id: 2, detail: "Utilized Google's TensorFlow machine learning to make predictions on code-change data"},
            {id: 3, detail: "Developed a web dashboard using ReactJS"}
        ],
        "skills" : "Neo4j, Python, ReactJS, SQL, TensorFlow"
    }
]

export default Coop;